name: Run All Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  bdd-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './tdd-bdd/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./tdd-bdd
      run: npm ci
    
    - name: Run BDD tests
      working-directory: ./tdd-bdd
      run: npm run test:cucumber

  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './backend-testing/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./backend-testing
      run: npm ci
    
    - name: Run backend tests
      working-directory: ./backend-testing
      run: npm test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './frontend-testing/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend-testing
      run: npm ci
    
    - name: Run unit tests
      working-directory: ./frontend-testing
      run: npm test
      
    - name: Build frontend
      working-directory: ./frontend-testing
      run: npm run build
    
    - name: Run E2E tests
      working-directory: ./frontend-testing
      run: |
        npm run start:test &
        npm run cypress:run
